import type { DataCatalogCard, DataSourceCard, PipelineMiniCard } from "@/types";

export const dataSources: DataSourceCard[] = [
  { key: "huggingface", name: "Hugging Face", subtitle: "社区开源数据", icon: "🤗" },
  { key: "haina", name: "海纳数据枢纽", subtitle: "平台候选数据", icon: "🌊" },
  { key: "georemote", name: "GeoRemote", subtitle: "遥感本地数据", icon: "🛰️" },
];

export const dataCatalogCards: DataCatalogCard[] = [
  {
    id: 1,
    title: "Sentinel-2 l2a",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "Sentinel-2 L2A 多光谱地表反射率数据，覆盖浙江省域，主要用于 GeoOrigin 遥感嵌入模型预训练、区域表征学习与多时相遥感分析。",
    region: "浙江省",
    beginTime: "2025-01",
    endTime: "2026-02",
    resolution: "10m",
    size: "1.2TB",
    samples: "32万",
    stars: 6,
    license: "OSS / Public",
    domain: "遥感预训练",
    format: "GeoTIFF",
    modality: ["多光谱"],
    scope: ["预训练"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/public/zhejiang/GEE-download/2025_S2",
  },
  {
    id: 2,
    title: "Sentinel-1 GRD",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "Sentinel-1 SAR 雷达后向散射数据，包含 VV、VH 等极化信息，可用于全天候地表结构建模、灾害监测与遥感预训练。",
    region: "浙江省",
    beginTime: "2025-01",
    endTime: "2026-02",
    resolution: "10m",
    size: "860GB",
    samples: "18万",
    stars: 5,
    license: "OSS / Public",
    domain: "遥感预训练",
    format: "GeoTIFF",
    modality: ["SAR", "雷达"],
    scope: ["预训练", "变化检测", "地表结构"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/public/zhejiang/GEE-download/2025_S1",
  },
  {
    id: 3,
    title: "Landsat 8/9 L2",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "Landsat 8/9 Collection 2 Level-2 地表反射率与热红外数据，适合长时间序列分析、地表温度估计和跨传感器预训练。",
    region: "浙江省",
    beginTime: "2025-01",
    endTime: "2026-02",
    resolution: "30m",
    size: "640GB",
    samples: "12万",
    stars: 5,
    license: "OSS / Public",
    domain: "遥感预训练",
    format: "GeoTIFF",
    modality: ["多光谱", "热红外"],
    scope: ["预训练", "温度估计", "时序分析"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/public/zhejiang/GEE-download/2025_L89",
  },
  {
    id: 4,
    title: "High Resolution RGB",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "杭州高分辨率 RGB 影像数据，适用于城市建筑、道路、水体、地块等细粒度地物识别与视觉语言模型训练。",
    region: "杭州市",
    beginTime: "2024-01",
    endTime: "2025-12",
    resolution: "0.3m",
    size: "2.8TB",
    samples: "45万",
    stars: 7,
    license: "Internal",
    domain: "遥感预训练",
    format: "GeoTIFF",
    modality: ["RGB", "光学"],
    scope: ["预训练", "目标检测", "城市模型"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/Hangzhou_TimeSeries2025",
  },
  {
    id: 5,
    title: "SRTM DEM",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "SRTM 数字高程模型数据，提供地形高程信息，可作为遥感嵌入、城市高度估计、温度建模和地形因子分析的辅助模态。",
    region: "全球",
    beginTime: "2000-02",
    endTime: "2000-02",
    resolution: "30m",
    size: "120GB",
    samples: "8万",
    stars: 4,
    license: "OSS / Public",
    domain: "地形建模",
    format: "GeoTIFF",
    modality: ["DEM", "高程", "SAR"],
    scope: ["预训练", "地形分析", "城市模型"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/Opensourcedata/SRTM",
  },
  {
    id: 6,
    title: "WorldCereal",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "WorldCereal 全球农作物与耕地产品数据，可用于农业场景识别、作物分布分析、土地利用建模和遥感嵌入评估。",
    region: "浙江省",
    beginTime: "2021-01",
    endTime: "2021-12",
    resolution: "10m",
    size: "96GB",
    samples: "6万",
    stars: 4,
    license: "OSS / Public",
    domain: "农业遥感",
    format: "GeoTIFF",
    modality: ["土地覆盖", "农作物"],
    scope: ["农业识别", "预训练评估", "土地利用"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/Opensourcedata/olmodata/WorldCereal_2021_Global_Products",
  },
  {
    id: 7,
    title: "ESA WorldCover 10m",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "ESA WorldCover 10 米全球土地覆盖数据，包含建筑、林地、水体、耕地、草地等类别，可作为地物先验与遥感预训练标签参考。",
    region: "浙江省",
    beginTime: "2021-01",
    endTime: "2021-12",
    resolution: "10m",
    size: "180GB",
    samples: "10万",
    stars: 5,
    license: "PuOSS / Publicblic",
    domain: "土地覆盖",
    format: "GeoTIFF",
    modality: ["土地覆盖", "分类标签"],
    scope: ["预训练", "语义分割", "地物识别"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/Opensourcedata/olmodata/ESA_WorldCover_10m2021v200/",
  },
  {
    id: 8,
    title: "AEF Earth Embedding",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "AlphaEarth / AEF 地球表征嵌入数据，可用于区域相似性检索、代表性采样点选择、生态地理分区评估和下游任务迁移分析。",
    region: "浙江省",
    beginTime: "2024-01",
    endTime: "2024-12",
    resolution: "10m",
    size: "420GB",
    samples: "25万",
    stars: 8,
    license: "OSS / Public",
    domain: "遥感嵌入",
    format: "Parquet",
    modality: ["Embedding", "多模态表征"],
    scope: ["嵌入检索", "下游评估", "代表性采样"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/aef-zhejiang/2024",
  },
  {
    id: 9,
    title: "OpenStreetMap Vector",
    source: "georemote",
    sourceName: "GeoRemote",
    description:
      "OpenStreetMap 开放矢量数据，包含道路、水系、建筑、兴趣点、行政边界等要素，可用于遥感影像语义增强、栅格—矢量对齐和城市空间结构建模。",
    region: "浙江省",
    beginTime: "2025-01",
    endTime: "2026-02",
    resolution: "矢量",
    size: "180GB",
    samples: "120万",
    stars: 6,
    license: "OSS / Public",
    domain: "开放矢量数据",
    format: "GeoJSON / Shapefile / Parquet",
    modality: ["矢量", "道路", "建筑", "POI", "水系"],
    scope: ["栅格矢量对齐", "城市模型", "遥感嵌入"],
    projects: [],
    suitableModels: [],
    status: "available",
    storageStatus: "local",
    storagePath: "/mnt_llm_A100_V1/datasets/Opensourcedata/OpenStreetMap",
  },
  {
    id: 10,
    title: "High Resolution Canopy Height Maps",
    source: "paper",
    sourceName: "paper",
    description:
      "WRI 与 Meta 发布的高分辨率冠层高度图数据，基于高分辨率 Maxar 卫星影像和机器学习模型生成，提供全球和区域尺度的冠层高度信息，可用于森林结构建模、碳汇评估、生态环境分析、遥感嵌入评估与城市绿地结构分析。",
    region: "全球 / 浙江省可裁剪",
    beginTime: "2016-01",
    endTime: "2024-12",
    resolution: "1m",
    size: "未知",
    samples: "未知",
    stars: 6,
    license: "CC-BY-4.0",
    domain: "森林与生态遥感",
    format: "COG / GeoTIFF",
    modality: ["冠层高度", "森林结构", "生态环境"],
    scope: ["生态监测", "碳汇评估", "遥感嵌入评估", "城市绿地分析"],
    projects: [],
    suitableModels: [],
    status: "planned",
    storageStatus: "drive",
    storagePath: "https://registry.opendata.aws/dataforgood-fb-forests/",
    url: "https://registry.opendata.aws/dataforgood-fb-forests/",
  },
];

export const pipelineCards: PipelineMiniCard[] = [
  {
    id: 1,
    projectSlug: "geoorigin",
    modelName: "GeoOrigin 遥感嵌入模型",
    tag: "embedding",
    title: "GeoOrigin 多模态数据管线",
    description: "从已有数据集读取光学、SAR、土地覆盖、高程等模态，统一完成裁切、重采样、对齐和训练样本索引生成。",
    inputs: ["Sentinel-2", "Sentinel-1", "WorldCover", "DEM"],
    steps: ["读取", "质检", "重采样", "对齐", "索引", "导出"],
    outputs: ["多模态预训练数据", "样本索引", "质量报告"],
    href: "/projects/embedding/models/geoorigin-embedding/pipeline",
  },
];
