import type { DataCatalogCard, DataSourceCard, PipelineMiniCard } from "@/types";

export const dataSources: DataSourceCard[] = [
  { key: "huggingface", name: "Hugging Face", subtitle: "社区开源数据", icon: "🤗" },
  { key: "haina", name: "海纳数据枢纽", subtitle: "平台候选数据", icon: "🌊" },
  { key: "georemote", name: "GeoRemote", subtitle: "遥感本地数据", icon: "🛰️" },
];

export const dataCatalogCards: DataCatalogCard[] = [
  {
    id: 1,
    title: "Sentinel-2 Zhejiang Multispectral v1",
    source: "internal",
    sourceName: "已有数据集",
    description: "面向 GeoOrigin 遥感嵌入模型的 Sentinel-2 多光谱预处理数据，已完成云掩膜、重采样与切片索引。",
    size: "1.2TB",
    samples: "56万",
    stars: 8,
    license: "Internal",
    domain: "遥感预训练",
    format: "COG / Parquet",
    modality: ["光学", "多光谱"],
    scope: ["预训练", "下游评测"],
    projects: ["GeoOrigin"],
    suitableModels: ["遥感嵌入模型"],
    status: "available",
    storagePath: "/data/geoorigin/sentinel2/zhejiang_v1",
  },
  {
    id: 2,
    title: "Sentinel-1 Zhejiang SAR v1",
    source: "internal",
    sourceName: "已有数据集",
    description: "覆盖浙江区域的 Sentinel-1 VV/VH SAR 预处理数据，用于与光学数据进行多模态对齐。",
    size: "680GB",
    samples: "32万",
    stars: 6,
    license: "Internal",
    domain: "遥感预训练",
    format: "GeoTIFF",
    modality: ["SAR", "VV/VH"],
    scope: ["预训练"],
    projects: ["GeoOrigin"],
    suitableModels: ["遥感嵌入模型"],
    status: "available",
    storagePath: "/data/geoorigin/sentinel1/zhejiang_v1",
  },
  {
    id: 3,
    title: "WorldCover China 10m v1",
    source: "internal",
    sourceName: "已有数据集",
    description: "中国区域 10m 土地覆盖标签数据，可作为 GeoOrigin 预训练辅助监督和下游评估标签。",
    size: "210GB",
    samples: "全国覆盖",
    stars: 5,
    license: "Public dataset",
    domain: "土地覆盖",
    format: "COG",
    modality: ["土地覆盖", "标签"],
    scope: ["下游评测", "预训练"],
    projects: ["GeoOrigin", "One Terra"],
    suitableModels: ["遥感嵌入模型", "One Terra"],
    status: "available",
    storagePath: "/data/geoorigin/worldcover/china_v1",
  },
  {
    id: 4,
    title: "Urban RGB High Resolution Dataset",
    source: "haina",
    sourceName: "海纳数据枢纽",
    description: "城市高分辨率 RGB 遥感影像候选数据，适合城市高度估计、建筑提取与城市空间建模。",
    size: "待确认",
    samples: "待确认",
    stars: 7,
    license: "需确认",
    domain: "城市建模",
    format: "GeoTIFF",
    modality: ["RGB", "高分辨率"],
    scope: ["城市建模", "下游评测"],
    projects: ["城市模型", "GeoOrigin"],
    suitableModels: ["城市模型", "遥感嵌入模型"],
    status: "planned",
    url: "#",
  },
  {
    id: 5,
    title: "Remote Sensing Multimodal Pretrain Collection",
    source: "huggingface",
    sourceName: "Hugging Face",
    description: "来自 Hugging Face 的遥感多模态预训练候选数据集合，可用于扩展 GeoOrigin 数据源池。",
    size: "按数据集确认",
    samples: "开放数据",
    stars: 12,
    license: "OSS / Public",
    domain: "遥感预训练",
    format: "Parquet / WebDataset",
    modality: ["光学", "SAR", "标签"],
    scope: ["预训练"],
    projects: ["GeoOrigin"],
    suitableModels: ["遥感嵌入模型", "One Terra"],
    status: "candidate",
    url: "https://huggingface.co/datasets",
  },
  {
    id: 6,
    title: "Heat Risk LST & Climate Auxiliary Data",
    source: "haina",
    sourceName: "海纳数据枢纽",
    description: "面向热风险估计模型的地表温度、气象变量与城市环境辅助数据。",
    size: "待确认",
    samples: "城市区域",
    stars: 4,
    license: "需确认",
    domain: "热风险",
    format: "NetCDF / GeoTIFF",
    modality: ["LST", "气象"],
    scope: ["热风险", "城市建模"],
    projects: ["热风险估计", "城市模型"],
    suitableModels: ["热风险估计模型"],
    status: "candidate",
    url: "#",
  },
];

export const pipelineCards: PipelineMiniCard[] = [
  {
    id: 1,
    projectSlug: "geoorigin",
    modelName: "GeoOrigin 遥感嵌入模型",
    tag: "embedding",
    title: "GeoOrigin 多模态数据管线",
    description: "从已有数据集读取光学、SAR、土地覆盖、高程等模态，统一完成裁切、重采样、对齐和训练样本索引生成。",
    inputs: ["Sentinel-2", "Sentinel-1", "WorldCover", "DEM"],
    steps: ["读取", "质检", "重采样", "对齐", "索引", "导出"],
    outputs: ["多模态预训练数据", "样本索引", "质量报告"],
    href: "/projects/embedding/models/geoorigin-embedding/pipeline",
  },
];
