import type { Achievement, DashboardSummary, PersonalMember, Project } from "@/types";

export const teamGroups = [
  {
    id: 1,
    key: "data",
    title: "数据组",
    short_title: "Data Team",
    description: "负责多源遥感数据、矢量数据、气象数据、地形数据、城市数据等的采集、清洗、标准化、切片、入库与质量检查。",
    keywords: ["多源数据", "数据治理", "质量检查"],
  },
  {
    id: 2,
    key: "embedding",
    title: "遥感嵌入模型组",
    short_title: "Embedding Team",
    description: "负责遥感影像嵌入模型的数据组织、模型训练、特征提取、下游评测与生态地理代表性采样点分析。",
    keywords: ["表征学习", "特征提取", "下游评测"],
  },
  {
    id: 3,
    key: "vlm",
    title: "遥感视觉语言模型组",
    short_title: "VLM Team",
    description: "负责遥感图像理解、开放词汇分割、指代分割、推理分割、目标检测、多模态问答与视觉语言模型能力构建。",
    keywords: ["开放词汇", "多模态理解", "推理分割"],
  },
  {
    id: 4,
    key: "temperature",
    title: "温度模型组",
    short_title: "Temperature Team",
    description: "负责城市热风险估计、地表温度反演、热岛效应分析、城市空间热暴露评估与下游应用验证。",
    keywords: ["热风险", "地表温度", "城市热暴露"],
  },
];

export const projects: Project[] = [
  {
    id: 1,
    name: "遥感嵌入模型",
    slug: "embedding",
    subtitle: "面向遥感多模态嵌入范式的模型研发项目",
    description: "对标 Google DeepMind AlphaEarth Foundations（AEF） 的卫星嵌入范式，面向中国自然资源调查监测、国土空间治理和生态环境监管需求，构建一套自主可控、可持续迭代的遥感影像表征基础模型。",
    achieve: "第一阶段预训练完成，变化模型",
    next_stage: "拓展至全国AEF构建",
    status: "active",
    owner: "王振",
    tags: ["遥感多模态", "地球表征", "AEF", "GeoAI"],
    metrics: { datasets: 12, models: 3, samples: "4,586", coverage: "2.56 km²" }
  },
  {
    id: 2,
    name: "热风险估计模型",
    slug: "heat-risk",
    subtitle: "面向城市热环境与风险治理的遥感估计模型",
    description: "结合地表温度、地形、土地覆盖、城市形态与人口暴露数据，构建城市热风险估计与分级展示能力。",
    stage: "指标体系与样例区域验证",
    status: "active",
    owner: "华梓强",
    tags: ["热风险", "城市", "LST", "风险评估"],
    metrics: { datasets: 5, models: 1, areas: "3 个样例城市", outputs: "风险等级图" }
  },
  {
    id: 3,
    name: "One Terra",
    slug: "one-terra",
    subtitle: "统一地球表征与全球尺度模型项目",
    description: "面向遥感场景中复杂地物识别与开放语义理解需求，构建遥感领域开放词汇全景分割模型，打通传统遥感解译中\"类别封闭、任务割裂、泛化不足\"的瓶颈。",
    stage: "总体方案设计与数据源梳理",
    status: "active",
    owner: "郑黄河",
    tags: ["全球尺度", "全景分割", "目标检测", "地物感知"],
    metrics: { datasets: 7, models: 1, regions: "全球候选", tasks: "分类/分割/回归" }
  },
  {
    id: 4,
    name: "城市模型",
    slug: "city-model",
    subtitle: "面向城市空间理解和治理应用的模型体系",
    description: "面向城市长期演化监测和多场景治理应用，构建覆盖 0.3 米到 30 米空间分辨率、连续 25 年时间跨度的城市统一编码体系，实现对城市空间结构、建设强度、功能形态和演化过程的精细表达。",
    stage: "应用场景与数据资产整合",
    status: "active",
    owner: "华梓强",
    tags: ["城市计算", "空间智能", "功能区", "治理应用"],
    metrics: { datasets: 4, models: 1, cities: "5 个候选城市", demos: 2 }
  }
];

export const personalMembers: PersonalMember[] = [
  {
    id: 0,
    name: "刘婧",
    team_group_id: null,
    team_group: null,
    title: "研究员 / 博士",
    role: "遥感团队负责人",
    description: "负责天地一体遥感智能模型体系的总体规划、技术架构设计与工程化落地，统筹数据组、遥感嵌入模型组、遥感视觉语言模型组和温度模型组协同推进。",
    projects: ["总体规划", "技术架构", "工程落地", "项目统筹"],
    isTeamLead: true,
  },
  {
    id: 1,
    name: "王子群",
    role: "数据组负责人",
    team_group_id: 1,
    team_group: teamGroups[0],
    researchDirection: "数据资产综合治理",
    recentWork: "完成二期种子班项目数据综合统筹",
    projects: ["one-terra", "city-model"],
  },
  {
    id: 2,
    name: "王笑",
    team_group_id: 1,
    team_group: teamGroups[0],
    researchDirection: "数据管理与规划",
    recentWork: "完成二期种子班项目数据处理规划与统筹",
    projects: ["embedding", "city-model"],
  },
  {
    id: 3,
    name: "王英瑾",
    team_group_id: 1,
    team_group: teamGroups[0],
    researchDirection: "温度推理城市规划、算力预算与省域推理",
    recentWork: "确定新增温度推理城市清单，核算并提交算力预算申请文件；按照审核后的温度推理排期推进温度推理；同步推进广西省高度推理、高度拼接、分割推理、分割拼接、高度建模、车辆识别和车辆在途任务，并参与遥感相关数据整理与汇总。",
    projects: ["heat-risk", "city-model"],
  },
  {
    id: 4,
    name: "郑黄河",
    role: "遥感视觉语言模型组负责人",
    team_group_id: 3,
    team_group: teamGroups[2],
    researchDirection: "遥感分割模型评测与自然资源任务支持",
    recentWork: "参加自然资源部种子班并支持第二组相关任务，配合完成任务计划制定与排期；完成 SCD-SAM 在自然资源部任务相关数据集上的评测。",
    projects: ["one-terra"],
  },
  {
    id: 5,
    name: "张德义",
    team_group_id: 3,
    team_group: teamGroups[2],
    researchDirection: "遥感变化检测数据处理与模型评测",
    recentWork: "参加自然资源种子班二期并支持相关任务；完成 S2Looking 数据集 256×256 切片，在 S2Looking 与 SYSU 数据集上训练和测试 ChangeDINO 模型，并进一步测试其在 TERRA-CD、CLCD、OSCD 等数据集上的泛化效果。",
    projects: ["one-terra"],
  },
  {
    id: 6,
    name: "申慧",
    team_group_id: 3,
    team_group: teamGroups[2],
    researchDirection: "遥感多任务训练策略与变化检测语言模型",
    recentWork: "基于前期新增下载和清洗的 8 个数据集，以及两版不同数据配比训练配置，结合算力申请情况拉起训练，并根据阶段性评测结果调整训练策略；同步推进多任务协同优化策略和变化检测结合语言模型的研究调研。",
    projects: ["one-terra"],
  },
  {
    id: 7,
    name: "张航",
    team_group_id: 3,
    team_group: teamGroups[2],
    researchDirection: "遥感视觉分割算法研究",
    recentWork: "完成云栖种子班期间工作汇总与总结报告撰写，并制作相关展示 PPT。",
    projects: ["one-terra"],
  },
  {
    id: 8,
    name: "李霄涵",
    team_group_id: 3,
    team_group: teamGroups[2],
    researchDirection: "OneTerra 大模型训练代码学习与任务支持",
    recentWork: "参加自然资源部种子班，按需完成相关任务并提供技术支持；学习 OneTerra 18B 训练代码，为后续模型训练和工程接入做准备。",
    projects: ["one-terra"],
  },
  {
    id: 9,
    name: "王振",
    role: "遥感嵌入模型组负责人",
    team_group_id: 2,
    team_group: teamGroups[1],
    researchDirection: "变化检测感知的影像矢量基础模型训练与评测",
    recentWork: "完成变化检测感知的影像矢量基础模型在 medium 级别数据集上的训练，数据规模约 29 万对矢量影像对，并完成训练后基础模型在 3 类以上变化检测评测集上的微调测评。",
    projects: ["embedding"],
  },
  {
    id: 10,
    name: "杨森",
    team_group_id: 2,
    team_group: teamGroups[1],
    researchDirection: "矢量嵌入编码与影像矢量联合建模",
    recentWork: "完善矢量嵌入编码、矢量生成相关调研，开展矢量影像联合建模模型框架调研，完成相关章节撰写，并参与讨论确定技术方案。",
    projects: ["embedding", "one-terra"],
  },
  {
    id: 11,
    name: "姬朋立",
    team_group_id: 2,
    team_group: teamGroups[1],
    researchDirection: "多目标尺度与多空间分辨率统一建模",
    recentWork: "完成遥感影像场景多目标尺度和多空间分辨率统一建模的调研与分享，明确对应的问题场景和技术路线。",
    projects: ["embedding"],
  },
  {
    id: 12,
    name: "李萧缘",
    team_group_id: 2,
    team_group: teamGroups[1],
    researchDirection: "遥感数据平台与嵌入数据管线建设",
    recentWork: "完成遥感数据平台基础框架建设，主要包含项目展示、已有数据集管理功能和遥感嵌入数据管线的初步搭建，形成可运行展示的基础版本。",
    projects: ["embedding", "遥感平台开发"],
  },
  {
    id: 13,
    name: "华梓强",
    role: "温度模型与推理组负责人",
    team_group_id: 4,
    team_group: teamGroups[3],
    researchDirection: "城市温度估计方法对比与跨域泛化实验",
    recentWork: "重点完成单城市和跨城市实验，并启动跨城市跨气候区与消融实验；Table 1 在 5 个城市评估 9 种方法，完成主要指标落表，重点分析 ERA5-Land、LST 和 HiUAT 表现；Table 2 跑通 5 组跨城实验，比较 Scratch、U-TL 与 HiUAT 的泛化能力；周末前初步跑通 Leave-One-City-Out 脚本和 3 个优先消融变体。",
    projects: ["heat-risk", "city-model"],
  },
  {
    id: 14,
    name: "林应琪",
    team_group_id: 4,
    team_group: teamGroups[3],
    researchDirection: "省域遥感推理、温度推理与论文实验组织",
    recentWork: "按照中国省份内部周进度排期推进广西省高度推理、高度拼接、分割推理、分割拼接、高度建模、车辆识别和车辆在途任务；落实温度论文框架，包括模板下载与撰写规划；准备与 GEO 开会内容，整理验证集数据并讨论 IBM 合作事项；同步推进温度推理排期任务。",
    projects: ["heat-risk", "city-model"],
  },
  {
    id: 15,
    name: "宋恺祥",
    team_group_id: 4,
    team_group: teamGroups[3],
    researchDirection: "遥感图文数据整理与大模型训练",
    recentWork: "继续推进遥感图文数据的整理和格式转换，完成基于 metron-core 以及 32B MoE 架构的模型训练。",
    projects: ["one-terra", "heat-risk"],
  },
  {
    id: 16,
    name: "宋飞翔",
    team_group_id: 4,
    team_group: teamGroups[3],
    researchDirection: "城市推理交付、省域数据推理与存储迁移",
    recentWork: "完成 10 个城市推理结果交付，继续推进广西数据推理，并将现有数据迁移到新 NAS。",
    projects: ["heat-risk", "city-model"],
  },
];

export const achievements: Achievement[] = [
  {
    id: 1,
    slug: "embedding-pipeline",
    title: "嵌入模型处理管线",
    type: "pipeline",
    description: "针对Sentinel-1、Sentinel-2、Landsat、RGB、WorldCover、SRTM等光学、地理模态的处理管线",
    tags: ["数据处理", "任务管理"],
    project_id: 1,
    authors_team_id: 2,
    authors_team: teamGroups[1],
    cover_text: "PIPE",
  },
  {
    id: 2,
    slug: "geoorigin-embedding-model",
    title: "GeoOrigin-Embedding",
    type: "可视化",
    description: "面向自然资源业务的国产遥感影像嵌入引擎，把可用于支撑分类、检索、变化发现和专题制图的通用地理空间特征资产。",
    tags: ["预训练", "多尺度融合", "统一表征"],
    project_id: 1,
    authors_team_id: 1,
    authors_team: teamGroups[0],
    cover_text: "Model",
  },
  {
    id: 3,
    slug: "heat-risk-indicator-system",
    title: "热风险估计指标体系",
    type: "可视化",
    description: "构建城市热风险估计的候选指标体系，包括热暴露、敏感性和适应能力。",
    tags: ["热风险", "指标体系"],
    project_id: 2,
    authors_team_id: 4,
    authors_team: teamGroups[3],
    cover_text: "Model",
  },
  {
    id: 4,
    slug: "heat-risk-sample-map",
    title: "城市热风险样例图",
    type: "可视化",
    description: "完成样例区域的热风险等级图展示，用于验证模型结果的可解释表达。",
    tags: ["风险预测", "地图"],
    project_id: 2,
    authors_team_id: 4,
    authors_team: teamGroups[3],
    cover_text: "Map",
  },
  {
    id: 5,
    slug: "one-terra-panoptic-segmentation",
    title: "One Terra 全景分割模型",
    type: "全景分割",
    description: "整理全球尺度地球观测数据源，为统一地球表征模型做准备。",
    tags: ["全景分割", "遥感分类模型", "零样本"],
    project_id: 3,
    authors_team_id: 3,
    authors_team: teamGroups[2],
    cover_text: "DownloadTask",
  },
  {
    id: 6,
    slug: "one-terra-object-detection",
    title: "One Terra 细粒度目标识别",
    type: "目标识别",
    description: "整理全球尺度地球观测数据源，为统一地球表征模型做准备。",
    tags: ["目标识别", "细粒度图像", "零样本"],
    project_id: 3,
    authors_team_id: 3,
    authors_team: teamGroups[2],
    cover_text: "DownloadTask",
  },
  {
    id: 7,
    slug: "city-task-decomposition",
    title: "城市空间任务拆解",
    type: "可视化",
    description: "梳理城市功能区识别、建筑理解、道路结构、人口活动等候选任务。",
    tags: ["城市模型", "城市规划"],
    project_id: 4,
    authors_team_id: 4,
    authors_team: teamGroups[3],
    cover_text: "Map",
  },
  {
    id: 8,
    slug: "city-height-estimation",
    title: "城市高度估计",
    type: "可视化",
    description: "利用高分辨率遥感影像估计城市建筑高度，快速生成城市三维空间模型，实现建筑高度、体量和分布的可视化表达，为城市精细治理、热岛分析和规划决策提供空间底座。",
    tags: ["城市模型", "任务体系"],
    project_id: 4,
    authors_team_id: 4,
    authors_team: teamGroups[3],
    cover_text: "Model",
  },
];

export const dashboardFallback: DashboardSummary = {
  project_count: projects.length,
  member_count: personalMembers.length,
  achievement_count: achievements.length,
  data_asset_count: 28,
  model_count: 6,
  projects,
  modality_stats: [
    { name: "Sentinel-1", count: 55032 },
    { name: "Sentinel-2", count: 55032 },
    { name: "Landsat-8", count: 55032 },
    { name: "RGB", count: 44186 },
    { name: "WorldCover", count: 4586 },
    { name: "SRTM", count: 4586 },
    { name: "OSM", count: 4586 }
  ],
  progress_stages: [
    { name: "数据采集", status: "done", ratio: 100 },
    { name: "数据处理", status: "done", ratio: 80 },
    { name: "模型训练", status: "active", ratio: 45 },
    { name: "模型评测", status: "pending", ratio: 20 },
    { name: "场景展示", status: "pending", ratio: 10 }
  ]
};
